public class Cycle{
String brand;
String model;
int year;
String color;
String countryOfOrigin;
static int wheels = 2;
public static void main(String args[]){
Cycle cycle1 = new Cycle();
cycle1.brand = "Hercules";
cycle1.model = "Dynor Pro";
cycle1.year = 2021;
cycle1.color = "Ivory white";
cycle1.countryOfOrigin = "India";
System.out.println("The details of cycle 1 :");
System.out.println("Brand:" + " " + cycle1.brand);
System.out.println("Model:" + " " + cycle1.model);
System.out.println("Year:" + " " + cycle1.year);
System.out.println("Color:" + " " + cycle1.color);
System.out.println("Country of origin:" + " " + cycle1.countryOfOrigin);
System.out.println("No of wheels:" + " " + wheels);
System.out.println("------------------------------------------------------------");
Cycle cycle2 = new Cycle();
cycle2.brand = "BSA";
cycle2.model = "Photon Ex";
cycle2.year = 2014;
cycle2.color = "Black";
cycle2.countryOfOrigin = "India";
System.out.println("The details of cycle 2 :");
System.out.println("Brand:" + " " + cycle2.brand);
System.out.println("Model:" + " " + cycle2.model);
System.out.println("Year:" + " " + cycle2.year);
System.out.println("Color:" + " " + cycle2.color);
System.out.println("Country of origin:" + " " + cycle2.countryOfOrigin);
System.out.println("No of wheels:" + " " + wheels);
System.out.println("------------------------------------------------------------");
Cycle cycle3 = new Cycle();
cycle3.brand = "Leader";
cycle3.model = "Leader Beast";
cycle3.year = 2022;
cycle3.color = "Green";
cycle3.countryOfOrigin = "China";
System.out.println("The details of cycle 3 :");
System.out.println("Brand:" + " " + cycle3.brand);
System.out.println("Model:" + " " + cycle3.model);
System.out.println("Year:" + " " + cycle3.year);
System.out.println("Color:" + " " + cycle3.color);
System.out.println("Country of origin:" + " " + cycle3.countryOfOrigin);
System.out.println("No of wheels:" + " " + wheels);
System.out.println("------------------------------------------------------------");
Cycle cycle4 = new Cycle();
cycle4.brand = "Avon";
cycle4.model = "Thrust 26T MTB";
cycle4.year = 2023;
cycle4.color = "Blue";
cycle4.countryOfOrigin = "Japan";
System.out.println("The details of cycle 4 :");
System.out.println("Brand:" + " " + cycle4.brand);
System.out.println("Model:" + " " + cycle4.model);
System.out.println("Year:" + " " + cycle4.year);
System.out.println("Color:" + " " + cycle4.color);
System.out.println("Country of origin:" + " " + cycle4.countryOfOrigin);
System.out.println("No of wheels:" + " " + wheels);
System.out.println("------------------------------------------------------------");
Cycle cycle5 = new Cycle();
cycle5.brand = "Urban Terrain";
cycle5.model = "Galaxy Max 7s 26T";
cycle5.year = 2024;
cycle5.color = "Yellow";
cycle5.countryOfOrigin = "India";
System.out.println("The details of cycle 5 :");
System.out.println("Brand:" + " " + cycle5.brand);
System.out.println("Model:" + " " + cycle5.model);
System.out.println("Year:" + " " + cycle5.year);
System.out.println("Color:" + " " + cycle5.color);
System.out.println("Country of origin:" + " " + cycle5.countryOfOrigin);
System.out.println("No of wheels:" + " " + wheels);
}
}